version: '3.8'

services:
  # Apache Common Log Format Generators (Multiple instances writing to same file)
  flog-common-1:
    image: mingrammer/flog
    container_name: flog-common-1
    command: >
      -f apache_common
      -o /logs/apache_common.log
      -t log
      -w
      -s 0.1s
      -d 25
    volumes:
      - /tmp/logs:/logs
    restart: unless-stopped

  flog-common-2:
    image: mingrammer/flog
    container_name: flog-common-2
    command: >
      -f apache_common
      -o /logs/apache_common.log
      -t log
      -w
      -s 0.1s
      -d 25
    volumes:
      - /tmp/logs:/logs
    restart: unless-stopped

  flog-common-3:
    image: mingrammer/flog
    container_name: flog-common-3
    command: >
      -f apache_common
      -o /logs/apache_common.log
      -t log
      -w
      -s 0.1s
      -d 25
    volumes:
      - /tmp/logs:/logs
    restart: unless-stopped

  flog-common-4:
    image: mingrammer/flog
    container_name: flog-common-4
    command: >
      -f apache_common
      -o /logs/apache_common.log
      -t log
      -w
      -s 0.1s
      -d 25
    volumes:
      - /tmp/logs:/logs
    restart: unless-stopped

  # Apache Combined Log Format Generators (Multiple instances writing to same file)
  flog-combined-1:
    image: mingrammer/flog
    container_name: flog-combined-1
    command: >
      -f apache_combined
      -o /logs/apache_combined.log
      -t log
      -w
      -s 0.02s
      -d 50
    volumes:
      - /tmp/logs:/logs
    restart: unless-stopped

  flog-combined-2:
    image: mingrammer/flog
    container_name: flog-combined-2
    command: >
      -f apache_combined
      -o /logs/apache_combined.log
      -t log
      -w
      -s 0.02s
      -d 50
    volumes:
      - /tmp/logs:/logs
    restart: unless-stopped

  flog-combined-3:
    image: mingrammer/flog
    container_name: flog-combined-3
    command: >
      -f apache_combined
      -o /logs/apache_combined.log
      -t log
      -w
      -s 0.02s
      -d 50
    volumes:
      - /tmp/logs:/logs
    restart: unless-stopped

  flog-combined-4:
    image: mingrammer/flog
    container_name: flog-combined-4
    command: >
      -f apache_combined
      -o /logs/apache_combined.log
      -t log
      -w
      -s 0.02s
      -d 50
    volumes:
      - /tmp/logs:/logs
    restart: unless-stopped

  flog-combined-5:
    image: mingrammer/flog
    container_name: flog-combined-5
    command: >
      -f apache_combined
      -o /logs/apache_combined.log
      -t log
      -w
      -s 0.02s
      -d 50
    volumes:
      - /tmp/logs:/logs
    restart: unless-stopped

  # Apache Error Log Format Generators (Multiple instances writing to same file)
  flog-error-1:
    image: mingrammer/flog
    container_name: flog-error-1
    command: >
      -f apache_error
      -o /logs/apache_error.log
      -t log
      -w
      -s 0.25s
      -d 10
    volumes:
      - /tmp/logs:/logs
    restart: unless-stopped

  flog-error-2:
    image: mingrammer/flog
    container_name: flog-error-2
    command: >
      -f apache_error
      -o /logs/apache_error.log
      -t log
      -w
      -s 0.25s
      -d 10
    volumes:
      - /tmp/logs:/logs
    restart: unless-stopped

  flog-error-3:
    image: mingrammer/flog
    container_name: flog-error-3
    command: >
      -f apache_error
      -o /logs/apache_error.log
      -t log
      -w
      -s 0.25s
      -d 10
    volumes:
      - /tmp/logs:/logs
    restart: unless-stopped

  flog-error-4:
    image: mingrammer/flog
    container_name: flog-error-4
    command: >
      -f apache_error
      -o /logs/apache_error.log
      -t log
      -w
      -s 0.25s
      -d 10
    volumes:
      - /tmp/logs:/logs
    restart: unless-stopped

volumes:
  logs: